### ISSUE TITLE
I encountered an "Uncaught TypeError: Failed to construct 'URL': Invalid URL" error while using the package.

### ISSUE THREAD

**Issue by jaewon4** [jgw96/web-ai-toolkit#5]
## Problem Description
I encountered an "Uncaught TypeError: Failed to construct 'URL': Invalid URL" error while using the package.

## Screenshot
<img width="283" alt="image" src="https://github.com/user-attachments/assets/4e34ab61-08a6-4bd5-be1d-dd031bb4bc13">

<img width="403" alt="image" src="https://github.com/user-attachments/assets/e64fae2b-e8f1-4cb0-90aa-92449aa8473e">

## Environment
- Operating System: Mac
- Browser: Chrome
- Node.js version: v22.6.0
- Package version: ^0.1.8

**Comment by maiconcarraro** [comment]
@jgw96 it seems to have a conflict w/ the new `@huggingface/transformers` alpha release, it works fine w/ `@xenova/transformers` imports, example:

replace 
```ts
import { pipeline, env } from '@huggingface/transformers';
```

with
```ts
import { pipeline, env } from '@xenova/transformers';
```

unfortunately it doesn't have the new fields that you are using like "device".

could be related to this: https://github.com/vitejs/vite/pull/17837

**Comment by jgw96** [comment]
Hey @jaewon4 , thanks for opening an issue! I will look into this later tonight.

**Comment by jaewon4** [comment]
thanks bro~

**Comment by jaewon4** [comment]
Thank you^^
